note/urls.py
#!/usr/bin/python
from django.urls import path
# from django.conf.urls import url
from . import views

app_name = 'note'
urlpatterns = [
    path('admin/', views.index, name='admin'),
    path('', views. index, name='index'),
    path('topics/', views.topics, name='topics'),
    path('entries/', views.entries, name='entries'),
    path('topics/<topic_id>', views.topic, name='topic'),
    path('new_topic/', views. new_topic, name='new_topic'),
    path('new_entry/<topic_id>', views.new_entry, name='new_entry'),
    path('edit_entry/<entry_id>', views.edit_entry, name='edit_entry'),
]

notebook/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from users import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('note.urls')),
    path('users/', include('users.urls', namespace='users')),
]

users/urls.py
#!/usr/bin/python
from django.urls import path
from . import views
# from django.contrib.auth.views import login 旧版本
from django.contrib.auth.views import LoginView

app_name = 'user'
urlpatterns = [
    # path('login/', login, {'template_name', 'user/login.html'}, name='admin'),
    path('login/', LoginView.as_view(template_name='users/login.html'), name="login"),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register, name='register'),
]

note/models.py
from django.db import models
import django.utils.timezone as timezone
from django.contrib.auth.models import User

# Create your models here.


class Topic(models.Model):
    '''单位工程名称'''
    text = models.CharField(default=timezone.now, max_length=200)
    date_added = models.DateTimeField(default=timezone.now)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = '单位工程'

    def __str__(self):
        return self.text


class Entry(models.Model):
    '''施工日志'''
    topic = models .ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models .DateTimeField(default=timezone.now)

    class Meta:
        verbose_name_plural = '施工日志'

    def __str__(self):
        """返回日志前50字"""
        if len(self.text)>20:
            return self.text[:20] + "..."
        else:
            return self.text[:20]

users/models.py
from django.db import models

# Create your models here.

note/forms.py
#!/usr/bin/python

from django import forms

from . models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 60})}

note/views.py
from django.shortcuts import render
from . models import Topic, Entry
from django.http import HttpResponseRedirect
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from . forms import TopicForm, EntryForm
from django.contrib.auth.decorators import login_required


# Create your views here.
def index(request):
    # 施工日志的主页
    return render(request, 'note/index.html')


@login_required
def topics(request):
    # 显示所有单位工程
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'note/topics.html', context)


@login_required
def topic(request, topic_id):
    # 显示一个单位工程及施工日志
    topic = Topic.objects.get(id=topic_id)
    # 确认请求的单位工程属于当前用户管理
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'note/topic.html', context)


@login_required
def entries(request):
    # 显示所有施工日志
    entries = Entry.objects.order_by('-date_added')
    context = {'entries': entries}
    return render(request, 'note/entries.html', context)


@login_required
def new_topic(request):
    # 添加单位工程
    if request.method != 'POST':
        # 未提交数据：创建一个新表单
        form = TopicForm()

    else:
        # POST提交的数据，对数据进行处理
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('note:topics'))
    context = {'form': form}
    return render(request, 'note/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    '''在指定单位工程中添加施工日志'''
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        # 未提交数据，创建一个空表单
        form = EntryForm()
    else:
        # post提交的数据，对数据进行处理
        form = EntryForm(data=request.POST)
        if form.is_valid:
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('note:topic', args=[topic_id]))
    context = {'topic': topic, 'form': form}
    return render(request, 'note/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    '''编辑施工日志'''
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    # 确认请求的单位工程属于当前用户管理
    if topic.owner != request.user:
        raise Http404
    if request.method != 'POST':
        # 初次请求，使用当前日志填充表单
        form = EntryForm(instance=entry)
    else:
        # post提交的数据，对数据进行处理
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid:
            form.save()
            return HttpResponseRedirect(reverse('note:topic', args=[topic.id]))
    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'note/edit_entry.html', context)

users/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponseRedirect
# from django.core.urlresolvers import reverse
from django.urls import reverse
from django.contrib.auth import logout
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm


def logout_view(request):
    """注销用户"""
    logout(request)
    return HttpResponseRedirect(reverse('note:index'))


def register(request):
    """注册新用户"""
    if request.method != 'POST':
        # 显示空的注册表单
        form = UserCreationForm()
    else:
        # 处理填写好的表单
        form = UserCreationForm(data=request.POST)
    
        if form.is_valid():
            new_user = form.save()
        # 让用户自动登录，再重定向到主页
            authenticated_user = authenticate(username=new_user.username, password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('note:index'))
    context = {'form': form}
    return render(request, 'users/register.html', context)

note/templates/note/base.html
<p>
	<a href="  {% url 'note:entries' %} "> <h2>施工日志</h2> </a>
	{% if user.is_authenticated %}
    你好！{{ user.username }}
    <a href="{% url 'users:logout' %}">注销</a>
    {% else %}
    <a href="{% url 'users:register' %}">请注册</a>
    <a href="{% url 'users:login' %}">请登录</a>
    {% endif %}
    <a href=" {% url 'note:topics' %}"> <h3>单位工程</h3> </a>
</p>

{% block content %}
{% endblock content %}

note/templates/note/edit_entry.html
{% extends "note/base.html" %}

{% block content %}
    <p>
    编辑<a href="{% url 'note:topic' topic.id %}">{{ topic }}</a>施工日志:
    </p>

	<form action="{% url 'note:edit_entry' entry.id %}" method='post'>
	  {%csrf_token%}
	  {{form.as_p}}
	  <button name="submit">保存日志</button>
	</form>

{% endblock content %}

note/templates/note/entries.html
{% extends "note/base.html" %}

{% block content %}

<ul>
  {% for entry in entries %}
    <li>
	    <p>{{entry.topic }}{{entry.date_added|date:'m-d'}}:</pp>
      <p>{{ entry.text }}</p>
	</li>
  {% empty %}
    <li>请按时填报施工日志</li>
  {% endfor %}
</ul>

{% endblock content %}

note/templates/note/index.html
{% extends "note/base.html" %}

{% block content %}


_____________________________________________________________________________
<p>每天8:00前，请填报前一天工程施工进展情况，班组主要工作和存在的问题。</p>
_____________________________________________________________________________


{% endblock content %}

note/templates/note/new_entry.html
{% extends "note/base.html" %}

{% block content %}
    <p>
    添加{{ topic }}施工日志:
    </p>

	<form action="{% url 'note:new_entry' topic.id %}" method='post'>
	  {%csrf_token%}
	  {{form.as_p}}
	  <button name="submit">提交日志</button>
	</form>

{% endblock content %}

note/templates/note/new_topic.html
{% extends "note/base.html" %}

{% block content %}
  <p>增加新的单位工程:</p>

	<form action="{% url 'note:new_topic' %}" method='post'>
	  {%csrf_token%}
	  {{form.as_p}}
	  <button name="submit">增加单位工程</button>
	</form>

{% endblock content %}

note/templates/note/topic.html
{% extends "note/base.html" %}

{% block content %}
<a href="{% url 'note:new_entry' topic.id %}"><h3>添加{{ topic }}日志</h3></a>
  <p>
	<h3>{{ topic }}施工日志：</h3>
	</p>
 <ul>
  {% for entry in entries %}
    <li>
		<p>{{entry.date_added|date:'Y-m-d'}}</p>
    <p>{{entry.text|linebreaks}}</p>
    <a href="{% url 'note:edit_entry' entry.id %}"><h4>修改日志</h4></a>
    </li>
  {% empty %}
    <li>
    请按时填报每日工作日志
	</li>
  {% endfor %}
  
  
</ul>
  
{% endblock content %}

note/templates/note/topics.html
{% extends "note/base.html" %}

{% block content %}

<ul>
  {% for topic in topics %}
    <li>
    <a href="{% url 'note:topic' topic.id %}">{{ topic }}</a>
	</li>
  {% empty %}
    <li>请增加单位工程</li>
  {% endfor %}
</ul>

<a href="{% url 'note:new_topic' %}">增加单位工程</a>

{% endblock content %}

users/templates/users/login.html
{% extends "note/base.html" %} 
{% block content %} 
  {% if form.errors %} 
 <p>你的用户名和密码错误，请再试一遍！</p> 
  {% endif %} 
 
  <form method="post" action="{% url 'users:login' %}"> 
    {% csrf_token %} 
    {{ form.as_p }} 
   <button name="提交">登录</button> 
  <input type="hidden" name="next" value="{% url 'note:index' %}" /> 
 </form>
 
 {% endblock content %}

users/templates/users/register.html
{% extends "note/base.html" %} 
{% block content %} 

<form method="post" action="{% url 'users:register' %}"> 
  {% csrf_token %} 
  {{ form.as_p }} 
  <button name="submit">用户注册</button> 
  <input type="hidden" name="next" value="{% url 'note:index' %}" /> 
</form>
 
 {% endblock content %}